import Head from 'next/head'
import { useVisitorData } from '@fingerprintjs/fingerprintjs-pro-react'
import { useState, useEffect } from 'react'
import axios from 'axios'

export default function Cart() {
    const [cartItems, setCartItems] = useState([])
    const { isLoading, data } = useVisitorData({ immediate: true })


    const totalQuantity = cartItems.map((item) => item.quantity)
        .reduce((a, b) => a + b, 0)

    const imageUrl = cartItems.map((item) => item.product_id.imageUrl)
    console.log(totalQuantity, imageUrl)

    useEffect(() => {
        const getCartItems = async () => {
            const visitorID = data?.visitorId
            const res = await axios.post('/api/getcart', { visitorID })
            setCartItems(res.data.data)
            console.log(res.data, visitorID);
        }
        getCartItems()
    }, [isLoading, data])
    return (
        <div className="">
            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div id='products' className="">
                    <h1 className="text-3xl font-semibold text-center py-10">Products</h1>
                    {cartItems.map((item, index) => (
                        <div key={index} >{item.id} {item.quantity} {item.product_id.imageUrl} {item.product_id.name} {item.amount} </div>
                    ))}
                </div>
            </main>

        </div>
    )
}